"""
Unit and Integration Tests for SKAI OS Control Engine
Founder & Sole Architect: Sumeet Kumar
"""
import sys
from pathlib import Path
import pytest

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from src_backend.app.services.os_control_service import OSControlService

@pytest.fixture
def temp_workspace(tmp_path):
    ws = tmp_path / "skai_test_ws"
    ws.mkdir(parents=True, exist_ok=True)
    return ws

def test_file_create_read_write_delete(temp_workspace):
    test_file = temp_workspace / "sample_note.txt"
    
    # 1. Create
    res_create = OSControlService.create_file(str(test_file), "Initial content for SKAI testing.")
    assert res_create["success"] is True
    assert test_file.exists()

    # 2. Read
    res_read = OSControlService.read_file(str(test_file))
    assert res_read["success"] is True
    assert "Initial content" in res_read["content"]

    # 3. Write / Append
    res_write = OSControlService.write_file(str(test_file), "\nSecond line appended.", append=True)
    assert res_write["success"] is True
    
    res_read_2 = OSControlService.read_file(str(test_file))
    assert "Second line appended." in res_read_2["content"]

    # 4. Delete
    res_delete = OSControlService.delete_file(str(test_file))
    assert res_delete["success"] is True
    assert not test_file.exists()

def test_folder_create_and_list(temp_workspace):
    sub_folder = temp_workspace / "sub_projects"
    res_folder = OSControlService.create_folder(str(sub_folder))
    assert res_folder["success"] is True
    assert sub_folder.exists()

    # Create dummy files inside
    (sub_folder / "file_a.txt").write_text("Alpha")
    (sub_folder / "file_b.py").write_text("print('Beta')")

    res_list = OSControlService.list_folder(str(sub_folder))
    assert res_list["success"] is True
    assert res_list["count"] == 2

def test_terminal_command_execution():
    res = OSControlService.run_terminal_command("echo SKAI_ONLINE")
    assert res["success"] is True
    assert "SKAI_ONLINE" in res["stdout"]
    assert res["exit_code"] == 0

def test_screenshot_capture():
    res = OSControlService.take_screenshot("test_verification_screen.png")
    assert res["success"] is True
    assert "thumbnail_data_uri" in res
    assert Path(res["path"]).exists()
    assert res["width"] > 0
    assert res["height"] > 0

def test_intelligent_local_search(temp_workspace):
    # Setup files with specific content
    doc_1 = temp_workspace / "financial_report.txt"
    doc_1.write_text("Quarterly revenue generated by SKAI assistant systems.")
    
    doc_2 = temp_workspace / "code_module.py"
    doc_2.write_text("# SK Enterprises neural pipeline logic\ndef test(): pass")

    res = OSControlService.search_local_files("revenue", base_dir=str(temp_workspace))
    assert res["success"] is True
    assert res["count"] >= 1
    assert any("financial_report.txt" in r["filename"] for r in res["results"])

def test_list_running_apps():
    res = OSControlService.list_running_apps(limit=10)
    assert res["success"] is True
    assert isinstance(res["apps"], list)
    assert res["count"] > 0
